// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/DbLedgerStorageDataFormats.proto

package org.apache.bookkeeper.bookie.storage.ldb;

public final class DbLedgerStorageDataFormats {
  private DbLedgerStorageDataFormats() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LedgerDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required bool exists = 1;
    boolean hasExists();
    boolean getExists();
    
    // required bool fenced = 2;
    boolean hasFenced();
    boolean getFenced();
    
    // required bytes masterKey = 3;
    boolean hasMasterKey();
    com.google.protobuf.ByteString getMasterKey();
  }
  public static final class LedgerData extends
      com.google.protobuf.GeneratedMessage
      implements LedgerDataOrBuilder {
    // Use LedgerData.newBuilder() to construct.
    private LedgerData(Builder builder) {
      super(builder);
    }
    private LedgerData(boolean noInit) {}
    
    private static final LedgerData defaultInstance;
    public static LedgerData getDefaultInstance() {
      return defaultInstance;
    }
    
    public LedgerData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.internal_static_LedgerData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.internal_static_LedgerData_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required bool exists = 1;
    public static final int EXISTS_FIELD_NUMBER = 1;
    private boolean exists_;
    public boolean hasExists() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public boolean getExists() {
      return exists_;
    }
    
    // required bool fenced = 2;
    public static final int FENCED_FIELD_NUMBER = 2;
    private boolean fenced_;
    public boolean hasFenced() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public boolean getFenced() {
      return fenced_;
    }
    
    // required bytes masterKey = 3;
    public static final int MASTERKEY_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString masterKey_;
    public boolean hasMasterKey() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.google.protobuf.ByteString getMasterKey() {
      return masterKey_;
    }
    
    private void initFields() {
      exists_ = false;
      fenced_ = false;
      masterKey_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasExists()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFenced()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMasterKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, exists_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, fenced_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, masterKey_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, exists_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, fenced_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, masterKey_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.LedgerData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.LedgerData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.LedgerData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.LedgerData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.LedgerData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.LedgerData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.LedgerData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.LedgerData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.LedgerData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.LedgerData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.LedgerData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.LedgerDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.internal_static_LedgerData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.internal_static_LedgerData_fieldAccessorTable;
      }
      
      // Construct using org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.LedgerData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        exists_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        fenced_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        masterKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.LedgerData.getDescriptor();
      }
      
      public org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.LedgerData getDefaultInstanceForType() {
        return org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.LedgerData.getDefaultInstance();
      }
      
      public org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.LedgerData build() {
        org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.LedgerData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.LedgerData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.LedgerData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.LedgerData buildPartial() {
        org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.LedgerData result = new org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.LedgerData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.exists_ = exists_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fenced_ = fenced_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.masterKey_ = masterKey_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.LedgerData) {
          return mergeFrom((org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.LedgerData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.LedgerData other) {
        if (other == org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.LedgerData.getDefaultInstance()) return this;
        if (other.hasExists()) {
          setExists(other.getExists());
        }
        if (other.hasFenced()) {
          setFenced(other.getFenced());
        }
        if (other.hasMasterKey()) {
          setMasterKey(other.getMasterKey());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasExists()) {
          
          return false;
        }
        if (!hasFenced()) {
          
          return false;
        }
        if (!hasMasterKey()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              exists_ = input.readBool();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              fenced_ = input.readBool();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              masterKey_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required bool exists = 1;
      private boolean exists_ ;
      public boolean hasExists() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public boolean getExists() {
        return exists_;
      }
      public Builder setExists(boolean value) {
        bitField0_ |= 0x00000001;
        exists_ = value;
        onChanged();
        return this;
      }
      public Builder clearExists() {
        bitField0_ = (bitField0_ & ~0x00000001);
        exists_ = false;
        onChanged();
        return this;
      }
      
      // required bool fenced = 2;
      private boolean fenced_ ;
      public boolean hasFenced() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public boolean getFenced() {
        return fenced_;
      }
      public Builder setFenced(boolean value) {
        bitField0_ |= 0x00000002;
        fenced_ = value;
        onChanged();
        return this;
      }
      public Builder clearFenced() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fenced_ = false;
        onChanged();
        return this;
      }
      
      // required bytes masterKey = 3;
      private com.google.protobuf.ByteString masterKey_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasMasterKey() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.google.protobuf.ByteString getMasterKey() {
        return masterKey_;
      }
      public Builder setMasterKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        masterKey_ = value;
        onChanged();
        return this;
      }
      public Builder clearMasterKey() {
        bitField0_ = (bitField0_ & ~0x00000004);
        masterKey_ = getDefaultInstance().getMasterKey();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:LedgerData)
    }
    
    static {
      defaultInstance = new LedgerData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:LedgerData)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_LedgerData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LedgerData_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/src/main/proto/DbLedgerStorageDataForm" +
      "ats.proto\"?\n\nLedgerData\022\016\n\006exists\030\001 \002(\010\022" +
      "\016\n\006fenced\030\002 \002(\010\022\021\n\tmasterKey\030\003 \002(\014B,\n(or" +
      "g.apache.bookkeeper.bookie.storage.ldbH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_LedgerData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_LedgerData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_LedgerData_descriptor,
              new java.lang.String[] { "Exists", "Fenced", "MasterKey", },
              org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.LedgerData.class,
              org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorageDataFormats.LedgerData.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
